####################################################
# LSrouter.py
# Name: Tran Duy Hieu
# HUID: 24022652
#####################################################
import json
import heapq

from router import Router
from packet import Packet

class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.neighbors = {}
        self.ls_database = {}
        self.seq = 0
        self.forwarding_table = {}
        self.ls_database[self.addr] = {
            "neighbors": {},
            "seq": 0
        }
        pass

    def _broadcast(self, excluded_port=None):
        content = json.dumps({
            "src": self.addr,
            "seq": self.seq,
            "neighbors": self.ls_database[self.addr]["neighbors"]
        })
        pkt = Packet(Packet.ROUTING, self.addr, None)
        pkt.content = content

        for port in self.neighbors:
            if port != excluded_port:
                self.send(port, pkt)    

    def _run_dijkstra(self):
        
        distance = {self.addr: 0}
        prev = {}

        pq = [(0, self.addr)]

        visited = set()

        while pq:
            cost, u = heapq.heappop(pq)

            if u in visited:
                continue
            visited.add(u)

            if u not in self.ls_database:
                continue

            neighbors_of_u = self.ls_database[u]["neighbors"]

            for v, link_cost in neighbors_of_u.items():
                new_cost = cost + link_cost
                if v not in distance or new_cost < distance[v]:
                    distance[v] = new_cost
                    prev[v] = u
                    heapq.heappush(pq, (new_cost, v))

        self.forwarding_table = {}

        for dest in distance:
            if dest == self.addr:
                continue

            hop = dest
            while prev.get(hop) != self.addr:
                hop = prev.get(hop)
                if hop is None:
                    break   

            if hop is None:
                continue

            for port, (neighbor_addr, _) in self.neighbors.items():
                if neighbor_addr == hop:
                    self.forwarding_table[dest] = port
                    break

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            if packet.dst_addr in self.forwarding_table:
                out_port = self.forwarding_table[packet.dst_addr]
                self.send(out_port, packet)
            pass
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            data = json.loads(packet.content)

            src      = data["src"]
            seq      = data["seq"]
            nb_dict  = data["neighbors"]

            if src in self.ls_database:
                if seq <= self.ls_database[src]["seq"]:
                    return

            self.ls_database[src] = {
                "neighbors": nb_dict,
                "seq": seq
            }

            self._run_dijkstra()

            flood_pkt = Packet(Packet.ROUTING, packet.src_addr, None)
            flood_pkt.content = packet.content
            for p in self.neighbors:
                if p != port:
                    self.send(p, flood_pkt)
            pass

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        self.neighbors[port] = (endpoint, cost)

        self.ls_database[self.addr]["neighbors"][endpoint] = cost

        self.seq += 1
        self.ls_database[self.addr]["seq"] = self.seq

        self._run_dijkstra()
        self._broadcast()
        pass

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        if port not in self.neighbors:
            return

        endpoint, _ = self.neighbors.pop(port)

        nb = self.ls_database[self.addr]["neighbors"]
        if endpoint in nb:
            del nb[endpoint]

        self.seq += 1
        self.ls_database[self.addr]["seq"] = self.seq

        self._run_dijkstra()

        self._broadcast()
        pass

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the link state of this router to all neighbors
            self.seq += 1
            self.ls_database[self.addr]["seq"] = self.seq
            self._broadcast()
            pass

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr})"